### ISSUE TITLE
performance compared to iptables?

### ISSUE THREAD

**Issue by dumbasPL** [tobik312/port-redir#1]
I wonder how the performance of something like this would compare to a simple iptables NAT

I feel like a user-mode proxy is an inferior solution since you lose a lot of benefits of the TCP flow control. + you also have to buffer the incoming data adding unnececary copies and delays.

The only advantage is that it's portable and doesn't require any extra permissions

**Comment by tobik312** [comment]
Redir also offers simple traffic control, but yes, you will never get all benefits of firewall software in my solution. The reason why I create this image, was simplicity. Redir/uredir was designed in UNIX way, it make only one thing, redirect traffict. In that way there is no sence to use additional firewall just to TCP flow control. This you should make on host machine.

But yeah, the performance comparison it's interesting, but this question should be addressed to the creator of redir/uredir.
